galaxy_info:
  author: Adam Haydon (https://github.com/ahaydon)
  description: Download QlikView Enterprise from GitHub
  company: Qlik (https://www.qlik.com)

  license: MIT

  min_ansible_version: 2.4

  platforms:
    - name: Windows
      versions:
        - 2016
        - 2019

  galaxy_tags:
    - qlik
    - qlikview
